server:
  log_level: info

metrics:
  global:
    remote_write:
      - url: ${GRAFANA_PROMETHEUS_URL}
        basic_auth:
          username: ${GRAFANA_USERNAME}
          password: ${GRAFANA_API_KEY}

  configs:
    - name: notion-agent
      scrape_configs:
        - job_name: notion-agent
          static_configs:
            - targets: ['localhost:8000']
          metrics_path: /metrics
          scrape_interval: 15s
